name: DEV CI/CD
on:
  push:
    branches:
      - feature/*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/checkout@v2
        with:
          node-version: 18
      - name: Install AWS CLI
        run: |
          # Install AWS CLI
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Install Elastic Beanstalk CLI
        run: |
          # Install Elastic Beanstalk CLI using apt
          sudo apt-get update
          sudo apt-get install -y awsebcli
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to Elastic Beanstalk
        run: |
          eb use ${{ secrets.EB_PROD_ENV_NAME }}
          eb deploy